version: '3.9'

services:

  postgres:

    image: pgvector/pgvector:pg16

    container_name: rag-postgres

    environment:
      POSTGRES_DB: ragdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

    ports:
      - "5432:5432"

  rag-app:

    build: .

    container_name: rag-app

    ports:
      - "8050:8050"

    depends_on:
      - postgres

    environment:
      SPRING_DATASOURCE_URL:
        jdbc:postgresql://postgres:5432/ragdb

      SPRING_DATASOURCE_USERNAME:
        postgres

      SPRING_DATASOURCE_PASSWORD:
        password