spring.application.name=rag-app

# DATABASE CONFIGURATION

#spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/ragdb
#spring.datasource.username=postgres
#spring.datasource.password=postgres

#spring.datasource.url=jdbc:postgresql://localhost:5432/ragdb
#spring.datasource.username=postgres
#spring.datasource.password=password

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# PostgreSQL dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# SERVER
server.port=8050

# FILE UPLOAD
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# SWAGGER
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

spring.ai.ollama.base-url=http://host.docker.internal:11434